### ISSUE TITLE
Pokemon Blue crashes since latest updates

### ISSUE THREAD

**Issue by Zabuzard** [trekawek/coffee-gb#23]
Since the latest updates, Pokemon Blue/Red crashes when loading the game world:

![gif](https://i.imgur.com/bMafsjg.gif)

Stacktrace:

```java
Exception in thread "Thread-1" java.lang.IndexOutOfBoundsException: Address: 40960
        at eu.rekawek.coffeegb.memory.Ram.getByte(Ram.java:43)
        at eu.rekawek.coffeegb.gpu.Fetcher.tick(Fetcher.java:133)
        at eu.rekawek.coffeegb.gpu.phase.PixelTransfer.tick(PixelTransfer.java:69)
        at eu.rekawek.coffeegb.gpu.Gpu.tick(Gpu.java:177)
        at eu.rekawek.coffeegb.Gameboy.tick(Gameboy.java:173)
        at eu.rekawek.coffeegb.Gameboy.run(Gameboy.java:132)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

It still worked fine with commit: https://github.com/trekawek/coffee-gb/commit/9f2ea204f8a49cdaf3adff05b58e144b11b07f04
But is now crashing, commit: https://github.com/trekawek/coffee-gb/commit/660ce4b4a048bfab2c491923ec3db8b7812e8ba1

So something in between those commits likely introduced a bug.

**Comment by trekawek** [comment]
Thanks! The new Window Internal Line Counter should be reset when the LCD is disabled. Fixed in 821b7f6bc8893bb2b92edd4c66525c025e66e6eb.
